version: "3"
services:
    redis:
        image: redis:4.0.11-alpine
        command: redis-server --appendonly yes --requirepass node-server
        volumes:
            - egg-redis:/data
        networks:
            - docker-node-server
        ports:
            - 6378:6379

    mongodb:
        image: mongo:3.6.7
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongodb
            MONGO_INITDB_DATABASE: node-server
        volumes:
            - egg-mongo:/data/db
            - ./init.d/mongo/:/docker-entrypoint-initdb.d
        networks:
            - docker-node-server
        ports:
            - 27016:27017

volumes:
    egg-mongo:
    egg-redis:

networks:
    docker-node-server:
        driver: bridge
